version: 2 
updates:
  # Fetch and update latest `npm` pkgs
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - dependencies
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '@types/node'
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

